baseURL = "https://x14ngch3n.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "Xiang Chen"

[params]
  socialIcons = [
    {name = "x", url = "https://x.com/XiangChen19699"},
    {name = "email", url = "mailto:xchenht@cse.ust.hk"},
    {name = "gmail", url = "mailto:x14ngch3n@gmail.com"},
    {name = "googlescholar", url = "https://scholar.google.com/citations?user=sAE_ZkEAAAAJ&hl=en"},
    {name = "googlemaps", url = "https://maps.app.goo.gl/zHPrM8VJkHFWhgGF6"},
    {name = "orcid", url = "https://orcid.org/0009-0007-0626-6888"},
    {name = "github", url = "https://github.com/x14ngch3n"}
  ]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/selfile-21.jpg"

  description = "PhD student in CSE, HKUST"
  # Enable dynamic footer with today's date
  lastUpdated = true
  metaKeywords = ["academic", "research"]
  showBackToTopButton = true # true or false for "back to top" button on posts and pages
  
  customHeadHTML = """
    <script defer src="https://cloud.umami.is/script.js" data-website-id="ab7a1a38-b3db-4f9d-838f-9078751fd5ae"></script>
  """

  customCommentHTML = """
    <script src="https://utteranc.es/client.js"
            repo="x14ngch3n/x14ngch3n.github.io"
            issue-term="title"
            theme="github-light"
            crossorigin="anonymous"
            async>
    </script>
  """

  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 4

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Favicon icon to display before the name
    pre = "<span data-feather='book'></span>"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    pre = "<span data-feather='tag'></span>"
    weight = 3

  [[menu.main]]
    name = "CV"
    url = "/pdf/cv.pdf"
    pre = "<span data-feather='user'></span>"
    weight = 4

  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    pre = "<span data-feather='file-text'></span>"
    weight = 5

  [[menu.main]]
    name = "Timeline"
    url = "https://xiangchen.notion.site/22a0ea3f3805809d9812e114ff925935?v=22a0ea3f380580d7b0ec000cf5e0b869"
    pre = "<span data-feather='calendar'></span>"
    weight = 6

  [[menu.main]]
    name = "Footprint"
    url = "https://maps.app.goo.gl/e4Ee7Xrv5Ahho4uj8"
    pre = "<span data-feather='map'></span>"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

[minify]
  minifyOutput = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'